# Generated by Django 3.0.6 on 2020-10-03 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(db_index=True, max_length=100, primary_key=True, serialize=False)),
                ('brand_name', models.CharField(max_length=100)),
                ('universe_htt_id', models.CharField(max_length=50)),
                ('brand_htt_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Barcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50)),
                ('format', models.CharField(default='-', max_length=10, verbose_name='format of barcode')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cosmetics.Product')),
            ],
        ),
        migrations.AddIndex(
            model_name='barcode',
            index=models.Index(fields=['code', 'format'], name='Cosmetics_b_code_2b3aa2_idx'),
        ),
        migrations.AddConstraint(
            model_name='barcode',
            constraint=models.UniqueConstraint(fields=('code', 'format'), name='unique_pair'),
        ),
    ]
