# Generated by Django 3.0.6 on 2020-10-03 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cosmetics', '0003_auto_20201003_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand_htt_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='universe_htt_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
