# Generated by Django 3.0.6 on 2020-10-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cosmetics', '0004_auto_20201003_1304'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='barcode',
            name='unique_pair',
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name', 'brand_name'], name='Cosmetics_p_name_818900_idx'),
        ),
        migrations.AddConstraint(
            model_name='barcode',
            constraint=models.UniqueConstraint(fields=('code', 'code_format'), name='barcode_unique_code_code_format'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('name', 'brand_name'), name='product_unique_name_brand_name'),
        ),
    ]
