# Generated by Django 3.0.6 on 2020-10-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cosmetics', '0006_auto_20201003_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcode',
            name='code_format',
            field=models.CharField(default='UPCEAN', max_length=10, verbose_name='format of barcode'),
        ),
    ]
