# Generated by Django 3.0.6 on 2020-10-03 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cosmetics', '0007_auto_20201003_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='brand_htt_id',
            new_name='brand_htt',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='universe_htt_id',
            new_name='universe_htt',
        ),
    ]
