# Generated by Django 3.0.6 on 2020-10-14 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Cosmetics', '0008_auto_20201003_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand_htt',
        ),
        migrations.RemoveField(
            model_name='product',
            name='universe_htt',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='eco_score',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='product',
            name='img_url',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='product',
            name='safety_score',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='product',
            name='total_score',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='product',
            name='zoo_score',
            field=models.IntegerField(default=-1),
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
