# Generated by Django 3.0.6 on 2020-10-14 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cosmetics', '0010_product_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cosmetics.Product'),
        ),
    ]
