# Generated by Django 3.0.6 on 2020-10-24 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cosmetics', '0013_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abbreviation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Restriction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('cas_number', models.CharField(max_length=100, null=True, unique=True)),
                ('ec_number', models.CharField(max_length=100, null=True, unique=True)),
                ('description', models.TextField()),
                ('functions', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Cosmetics.Function')),
                ('restrictions', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Cosmetics.Restriction')),
            ],
        ),
    ]
