# Generated by Django 3.0.6 on 2020-10-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cosmetics', '0014_abbreviation_function_ingredient_restriction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='cas_number',
            field=models.CharField(db_index=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='ec_number',
            field=models.CharField(db_index=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(db_index=True, max_length=250),
        ),
    ]
