# Generated by Django 3.0.6 on 2020-10-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cosmetics', '0015_auto_20201024_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='name',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='inci_name',
            field=models.TextField(blank=True, db_index=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='inn_name',
            field=models.TextField(blank=True, db_index=True),
        ),
    ]
