# Generated by Django 3.0.6 on 2020-11-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cosmetics', '0016_auto_20201024_1506'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Abbreviation',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='functions',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='restrictions',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='cas_dna_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='cas_dna_safety_score',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='cas_dna_url',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='cosmetics_info_safety_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='cosmetics_info_scientific_facts',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='cosmetics_info_url',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='cosmetics_info_what_is_it',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Function',
        ),
        migrations.DeleteModel(
            name='Restriction',
        ),
    ]
