# Generated by Django 3.0.6 on 2020-11-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_profile_img_url',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
