# Generated by Django 3.0.6 on 2020-11-23 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_user_user_profile_img_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_profile_img_url',
            new_name='profile_img_url',
        ),
    ]
